import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

function slugify(text: string): string {
  return text
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

async function main() {
  const email = process.env.SEED_ADMIN_EMAIL ?? "admin@shreejienterprise.com";
  const password = process.env.SEED_ADMIN_PASSWORD ?? "ChangeMe123!";
  const name = process.env.SEED_ADMIN_NAME ?? "Admin";

  const existing = await prisma.user.findUnique({ where: { email } });
  if (existing) {
    console.log(`Admin user already exists: ${email}`);
  } else {
    const hashed = await bcrypt.hash(password, 10);

    await prisma.user.create({
      data: {
        name,
        email,
        password: hashed,
        role: "ADMIN",
      },
    });

    console.log(`Created admin user: ${email} (password: ${password})`);
  }

  // --- 8 Required Categories ---
  const categories = [
    { name: "Architectural & Interior", slug: "architectural-interior" },
    { name: "Electrical & Electronics", slug: "electrical-electronics" },
    { name: "HVAC & Sheet Metal", slug: "hvac-sheet-metal" },
    { name: "Automotive Components", slug: "automotive-components" },
    { name: "Industrial & Machine Components", slug: "industrial-machine-components" },
    { name: "Furniture & Interior Components", slug: "furniture-interior-components" },
    { name: "Agriculture & Equipment", slug: "agriculture-equipment" },
    { name: "General Engineering & Job Work", slug: "general-engineering-job-work" },
  ];

  const categoryMap: Record<string, string> = {};
  for (const cat of categories) {
    const record = await prisma.portfolioCategory.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name },
      create: { name: cat.name, slug: cat.slug },
    });
    categoryMap[cat.slug] = record.id;
  }

  // --- 60 Required Portfolio Items with realistic B2B Job-Work Specs ---
  const portfolioItems = [
    // 01. Architectural & Interior (8 items)
    {
      name: "Decorative Wall Panel",
      categorySlug: "architectural-interior",
      industry: "Architecture & Interior",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / Stainless Steel (SS)",
      applicationType: "Job Work",
      description: "Custom laser-cut decorative wall panels featuring intricate geometric patterns, tailored for commercial and luxury residential interiors.",
      imageUrl: "/images/portfolio_safety_door.jpg",
      featured: true,
      displayOrder: 1,
    },
    {
      name: "Facade Panel",
      categorySlug: "architectural-interior",
      industry: "Architecture & Interior, Construction",
      processes: "Laser Cutting + CNC Bending",
      materials: "Aluminium / Stainless Steel (SS)",
      applicationType: "Custom Fabrication",
      description: "Precision-cut exterior architectural facade panels with high-tolerance perforation for building envelopes and solar shading.",
      imageUrl: "/images/portfolio_architectural_panel.jpg",
      featured: false,
      displayOrder: 2,
    },
    {
      name: "Ceiling Panel",
      categorySlug: "architectural-interior",
      industry: "Architecture & Interior",
      processes: "Laser Cutting + CNC Bending",
      materials: "Aluminium / Mild Steel (MS)",
      applicationType: "Job Work",
      description: "Lightweight acoustic and decorative sheet metal ceiling tiles manufactured with micro-perforations and clean corner bends.",
      imageUrl: "/images/cap_laser_cutting.jpg",
      featured: false,
      displayOrder: 3,
    },
    {
      name: "Partition Panel",
      categorySlug: "architectural-interior",
      industry: "Architecture & Interior, Furniture",
      processes: "Laser Cutting",
      materials: "Mild Steel (MS) / Stainless Steel (SS)",
      applicationType: "Job Work",
      description: "CNC laser-cut room divider and space partition screens engineered to client CAD drawings with deburred edges.",
      imageUrl: "/images/portfolio_safety_door.jpg",
      featured: false,
      displayOrder: 4,
    },
    {
      name: "Railing Panel",
      categorySlug: "architectural-interior",
      industry: "Construction, Architecture & Interior",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / Stainless Steel (SS)",
      applicationType: "Job Work",
      description: "High-strength safety railing infill panels with modern CNC cut motifs for balconies, terraces, and staircases.",
      imageUrl: "/images/portfolio_architectural_panel.jpg",
      featured: false,
      displayOrder: 5,
    },
    {
      name: "Staircase Railing Component",
      categorySlug: "architectural-interior",
      industry: "Construction, Architecture & Interior",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / Stainless Steel (SS)",
      applicationType: "Custom Fabrication",
      description: "Structural balustrade brackets and laser-cut steps designed for rapid on-site assembly and structural durability.",
      imageUrl: "/images/cap_cnc_bending.jpg",
      featured: false,
      displayOrder: 6,
    },
    {
      name: "Gate Design Panel",
      categorySlug: "architectural-interior",
      industry: "Architecture & Interior, Construction",
      processes: "Laser Cutting",
      materials: "Mild Steel (MS) / Galvanized Sheet",
      applicationType: "Job Work",
      description: "Heavy-gauge decorative sheet metal inserts for main entrance gates and compound boundary walls.",
      imageUrl: "/images/portfolio_safety_door.jpg",
      featured: false,
      displayOrder: 7,
    },
    {
      name: "Sunshade Panel",
      categorySlug: "architectural-interior",
      industry: "Architecture & Interior, Renewable Energy",
      processes: "Laser Cutting + CNC Bending",
      materials: "Aluminium / CRCA",
      applicationType: "Job Work",
      description: "Engineered louvers and perforated sunscreens designed to optimize natural ventilation and solar deflection.",
      imageUrl: "/images/portfolio_architectural_panel.jpg",
      featured: false,
      displayOrder: 8,
    },

    // 02. Electrical & Electronics (9 items)
    {
      name: "Control Panel Enclosure",
      categorySlug: "electrical-electronics",
      industry: "Electrical, Industrial Machinery",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / CRCA / GI",
      applicationType: "Job Work",
      description: "Custom sheet-metal enclosure with precision cutouts for pushbuttons, meters, cable glands, and hinged access door.",
      imageUrl: "/images/portfolio_enclosure.jpg",
      featured: true,
      displayOrder: 9,
    },
    {
      name: "Electrical Cabinet",
      categorySlug: "electrical-electronics",
      industry: "Electrical, Renewable Energy",
      processes: "Sheet Metal Fabrication",
      materials: "CRCA / Galvanized Sheet / SS",
      applicationType: "OEM Component",
      description: "Floor-standing multi-compartment electrical control cabinet with internal mounting sub-panels and sealing gaskets.",
      imageUrl: "/images/portfolio_enclosure.jpg",
      featured: true,
      displayOrder: 10,
    },
    {
      name: "Junction Box",
      categorySlug: "electrical-electronics",
      industry: "Electrical, Industrial Machinery",
      processes: "Laser Cutting + CNC Bending",
      materials: "Stainless Steel (SS) / CRCA",
      applicationType: "Standard Product",
      description: "IP65 rated dust and moisture-resistant sheet metal junction box with formed flanges and captive screw fixtures.",
      imageUrl: "/images/portfolio_enclosure.jpg",
      featured: false,
      displayOrder: 11,
    },
    {
      name: "Distribution Box",
      categorySlug: "electrical-electronics",
      industry: "Electrical, Construction",
      processes: "Laser Cutting + CNC Bending",
      materials: "CRCA / GI / Mild Steel (MS)",
      applicationType: "OEM Component",
      description: "Heavy-duty power distribution enclosure with busbar support cutouts and multi-tier DIN rail mounts.",
      imageUrl: "/images/portfolio_enclosure.jpg",
      featured: false,
      displayOrder: 12,
    },
    {
      name: "Meter Box",
      categorySlug: "electrical-electronics",
      industry: "Electrical, Renewable Energy",
      processes: "Laser Cutting + CNC Bending",
      materials: "CRCA / Galvanized Sheet",
      applicationType: "Job Work",
      description: "Tamper-proof utility meter box with viewing window cutouts, ventilation louvers, and padlock brackets.",
      imageUrl: "/images/portfolio_enclosure.jpg",
      featured: false,
      displayOrder: 13,
    },
    {
      name: "Battery Enclosure",
      categorySlug: "electrical-electronics",
      industry: "Renewable Energy, Automotive",
      processes: "Sheet Metal Fabrication",
      materials: "Mild Steel (MS) / Aluminium",
      applicationType: "Job Work",
      description: "Reinforced battery pack casing with thermal venting louvers and vibration-damped bracket mounts.",
      imageUrl: "/images/cap_custom_fabrication.jpg",
      featured: false,
      displayOrder: 14,
    },
    {
      name: "Cable Tray",
      categorySlug: "electrical-electronics",
      industry: "Electrical, Industrial Machinery",
      processes: "Laser Cutting + CNC Bending",
      materials: "Galvanized Sheet / GI / Stainless Steel (SS)",
      applicationType: "Job Work",
      description: "Perforated and ladder-type industrial cable management trays manufactured to high load-bearing standards.",
      imageUrl: "/images/cap_laser_cutting.jpg",
      featured: true,
      displayOrder: 15,
    },
    {
      name: "Rack Mount Panel",
      categorySlug: "electrical-electronics",
      industry: "Electrical, General Engineering",
      processes: "Laser Cutting + CNC Bending",
      materials: "Aluminium / CRCA",
      applicationType: "OEM Component",
      description: "19-inch standard server and audio rack front panels with precision laser-cut connector ports and captive nuts.",
      imageUrl: "/images/cap_custom_fabrication.jpg",
      featured: false,
      displayOrder: 16,
    },
    {
      name: "Switchboard Panel",
      categorySlug: "electrical-electronics",
      industry: "Electrical, Industrial Machinery",
      processes: "Laser Cutting + CNC Bending",
      materials: "CRCA / Mild Steel (MS)",
      applicationType: "Custom Fabrication",
      description: "Modular switchgear front facia plates and breaker escutcheons cut to exact electrical layout drawings.",
      imageUrl: "/images/portfolio_enclosure.jpg",
      featured: false,
      displayOrder: 17,
    },

    // 03. HVAC & Sheet Metal (7 items)
    {
      name: "HVAC Duct Flange",
      categorySlug: "hvac-sheet-metal",
      industry: "HVAC, Construction",
      processes: "Laser Cutting + CNC Bending",
      materials: "GI / Galvanized Sheet / Mild Steel (MS)",
      applicationType: "Job Work",
      description: "Precision-formed duct connector angle flanges with bolt hole patterns for leak-proof air distribution systems.",
      imageUrl: "/images/portfolio_heavy_bracket.jpg",
      featured: true,
      displayOrder: 18,
    },
    {
      name: "Louver Panel",
      categorySlug: "hvac-sheet-metal",
      industry: "HVAC, Industrial Machinery",
      processes: "Laser Cutting + CNC Bending",
      materials: "Aluminium / GI / Stainless Steel (SS)",
      applicationType: "Job Work",
      description: "Weather-resistant intake and exhaust louver panels with precision-formed blades for industrial ventilation.",
      imageUrl: "/images/cap_laser_cutting.jpg",
      featured: false,
      displayOrder: 19,
    },
    {
      name: "Air Grille",
      categorySlug: "hvac-sheet-metal",
      industry: "HVAC, Architecture & Interior",
      processes: "Laser Cutting",
      materials: "Aluminium / CRCA",
      applicationType: "Standard Product",
      description: "Laser-perforated air supply and return diffusers designed for uniform airflow and modern aesthetic integration.",
      imageUrl: "/images/portfolio_architectural_panel.jpg",
      featured: false,
      displayOrder: 20,
    },
    {
      name: "Fan Guard",
      categorySlug: "hvac-sheet-metal",
      industry: "HVAC, Industrial Machinery",
      processes: "Laser Cutting",
      materials: "Mild Steel (MS) / Stainless Steel (SS)",
      applicationType: "OEM Component",
      description: "Heavy-duty circular and square protective fan finger guards laser-cut with tight safety grid tolerances.",
      imageUrl: "/images/about_metal_part.jpg",
      featured: false,
      displayOrder: 21,
    },
    {
      name: "Fan Shroud",
      categorySlug: "hvac-sheet-metal",
      industry: "HVAC, Automotive",
      processes: "Laser Cutting + CNC Bending",
      materials: "Aluminium / CRCA / GI",
      applicationType: "Job Work",
      description: "Aerodynamic fan cowl and venturi housing designed to maximize heat exchanger airflow efficiency.",
      imageUrl: "/images/cap_cnc_bending.jpg",
      featured: false,
      displayOrder: 22,
    },
    {
      name: "Transition Piece",
      categorySlug: "hvac-sheet-metal",
      industry: "HVAC, Industrial Machinery",
      processes: "Sheet Metal Fabrication",
      materials: "GI / Stainless Steel (SS) / Mild Steel (MS)",
      applicationType: "Custom Fabrication",
      description: "Round-to-square and offset duct transitions fabricated with multi-stage CNC press brake forming.",
      imageUrl: "/images/cap_custom_fabrication.jpg",
      featured: false,
      displayOrder: 23,
    },
    {
      name: "HVAC Mounting Bracket",
      categorySlug: "hvac-sheet-metal",
      industry: "HVAC, Construction",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / Galvanized Sheet",
      applicationType: "Job Work",
      description: "Heavy-duty vibration-isolating mounting brackets for rooftop chillers, AHUs, and condenser units.",
      imageUrl: "/images/portfolio_heavy_bracket.jpg",
      featured: false,
      displayOrder: 24,
    },

    // 04. Automotive Components (8 items)
    {
      name: "Automotive Mounting Bracket",
      categorySlug: "automotive-components",
      industry: "Automotive, Industrial Machinery",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / CRCA",
      applicationType: "Job Work",
      description: "Heavy-gauge engine and transmission mounting brackets formed with high repeatability on 160-ton press brake.",
      imageUrl: "/images/about_metal_part.jpg",
      featured: true,
      displayOrder: 25,
    },
    {
      name: "Chassis Bracket",
      categorySlug: "automotive-components",
      industry: "Automotive, General Engineering",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS)",
      applicationType: "OEM Component",
      description: "High-tensile structural chassis stiffeners and sub-frame brackets with precision punched/slotted holes.",
      imageUrl: "/images/portfolio_heavy_bracket.jpg",
      featured: false,
      displayOrder: 26,
    },
    {
      name: "Heat Shield",
      categorySlug: "automotive-components",
      industry: "Automotive",
      processes: "Laser Cutting + CNC Bending",
      materials: "Aluminium / Stainless Steel (SS)",
      applicationType: "OEM Component",
      description: "Embossed and formed aluminium heat shields protecting sensitive vehicle components from exhaust temperatures.",
      imageUrl: "/images/cap_laser_cutting.jpg",
      featured: true,
      displayOrder: 27,
    },
    {
      name: "Battery Tray",
      categorySlug: "automotive-components",
      industry: "Automotive, Renewable Energy",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / CRCA",
      applicationType: "Job Work",
      description: "Automotive and EV battery mounting trays with retaining brackets and corrosion-resistant powder coat prep.",
      imageUrl: "/images/cap_custom_fabrication.jpg",
      featured: false,
      displayOrder: 28,
    },
    {
      name: "Exhaust Clamp",
      categorySlug: "automotive-components",
      industry: "Automotive",
      processes: "Laser Cutting + CNC Bending",
      materials: "Stainless Steel (SS) / Mild Steel (MS)",
      applicationType: "Standard Product",
      description: "Heavy-duty saddle and band exhaust clamps with precision formed radii and high clamping force.",
      imageUrl: "/images/about_metal_part.jpg",
      featured: false,
      displayOrder: 29,
    },
    {
      name: "Engine Cover",
      categorySlug: "automotive-components",
      industry: "Automotive, Agriculture",
      processes: "Sheet Metal Fabrication",
      materials: "CRCA / Aluminium",
      applicationType: "Custom Fabrication",
      description: "Formed protective engine side panels and timing inspection covers with oil-tight sealing flanges.",
      imageUrl: "/images/cap_custom_fabrication.jpg",
      featured: false,
      displayOrder: 30,
    },
    {
      name: "Seat Frame Component",
      categorySlug: "automotive-components",
      industry: "Automotive, Furniture",
      processes: "Laser Cutting + CNC Bending",
      materials: "CRCA / Mild Steel (MS)",
      applicationType: "OEM Component",
      description: "Lightweight, high-strength structural seat base plates and recliner link components.",
      imageUrl: "/images/about_metal_part.jpg",
      featured: false,
      displayOrder: 31,
    },
    {
      name: "Skid Plate",
      categorySlug: "automotive-components",
      industry: "Automotive",
      processes: "Laser Cutting + CNC Bending",
      materials: "Aluminium / Mild Steel (MS)",
      applicationType: "Custom Fabrication",
      description: "Underbody protection skid plates laser-cut with ventilation cutouts and drainage channels for off-road durability.",
      imageUrl: "/images/cap_prototype_bulk.jpg",
      featured: false,
      displayOrder: 32,
    },

    // 05. Industrial & Machine Components (8 items)
    {
      name: "Machine Base Frame",
      categorySlug: "industrial-machine-components",
      industry: "Industrial Machinery, General Engineering",
      processes: "Sheet Metal Fabrication",
      materials: "Mild Steel (MS)",
      applicationType: "Custom Fabrication",
      description: "Heavy structural machine base platforms fabricated from laser-cut plates and CNC formed box channels.",
      imageUrl: "/images/cap_prototype_bulk.jpg",
      featured: false,
      displayOrder: 33,
    },
    {
      name: "Machine Guard",
      categorySlug: "industrial-machine-components",
      industry: "Industrial Machinery",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / CRCA",
      applicationType: "Job Work",
      description: "OSHA-compliant protective safety covers and interlock housings for rotating machine parts.",
      imageUrl: "/images/about_metal_part.jpg",
      featured: true,
      displayOrder: 34,
    },
    {
      name: "Conveyor Bracket",
      categorySlug: "industrial-machine-components",
      industry: "Industrial Machinery",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / Stainless Steel (SS)",
      applicationType: "Job Work",
      description: "Roller support brackets, guide rail clamps, and drive mount plates for automated material handling lines.",
      imageUrl: "/images/portfolio_heavy_bracket.jpg",
      featured: false,
      displayOrder: 35,
    },
    {
      name: "Motor Cover",
      categorySlug: "industrial-machine-components",
      industry: "Industrial Machinery, Electrical",
      processes: "Laser Cutting + CNC Bending",
      materials: "CRCA / Mild Steel (MS)",
      applicationType: "OEM Component",
      description: "Protective electric motor cowls designed for optimized airflow cooling and impact protection.",
      imageUrl: "/images/cap_custom_fabrication.jpg",
      featured: false,
      displayOrder: 36,
    },
    {
      name: "Gearbox Cover",
      categorySlug: "industrial-machine-components",
      industry: "Industrial Machinery",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / Stainless Steel (SS)",
      applicationType: "Job Work",
      description: "Precision-cut gearbox inspection covers with high-tolerance bolt hole patterns for zero-leak sealing.",
      imageUrl: "/images/about_metal_part.jpg",
      featured: false,
      displayOrder: 37,
    },
    {
      name: "Equipment Enclosure",
      categorySlug: "industrial-machine-components",
      industry: "Industrial Machinery",
      processes: "Sheet Metal Fabrication",
      materials: "CRCA / Stainless Steel (SS)",
      applicationType: "Custom Fabrication",
      description: "Complete soundproof and dustproof industrial equipment housings with access panels and lift-off hinges.",
      imageUrl: "/images/portfolio_enclosure.jpg",
      featured: false,
      displayOrder: 38,
    },
    {
      name: "Support Bracket",
      categorySlug: "industrial-machine-components",
      industry: "Industrial Machinery, General Engineering",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS)",
      applicationType: "Job Work",
      description: "Heavy-duty gusseted support brackets engineered to withstand high static and dynamic industrial loads.",
      imageUrl: "/images/portfolio_heavy_bracket.jpg",
      featured: false,
      displayOrder: 39,
    },
    {
      name: "Pulley Guard",
      categorySlug: "industrial-machine-components",
      industry: "Industrial Machinery",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / GI",
      applicationType: "Job Work",
      description: "V-belt and timing belt safety guards featuring ventilation mesh and quick-release latch fixtures.",
      imageUrl: "/images/cap_laser_cutting.jpg",
      featured: false,
      displayOrder: 40,
    },

    // 06. Furniture & Interior Components (8 items)
    {
      name: "Table Base",
      categorySlug: "furniture-interior-components",
      industry: "Furniture, Architecture & Interior",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / Stainless Steel (SS)",
      applicationType: "Job Work",
      description: "Modern geometric sheet metal pedestal table legs and spider bases with concealed floor levelers.",
      imageUrl: "/images/cap_cnc_bending.jpg",
      featured: false,
      displayOrder: 41,
    },
    {
      name: "Chair Frame",
      categorySlug: "furniture-interior-components",
      industry: "Furniture",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / CRCA",
      applicationType: "OEM Component",
      description: "Ergonomic laser-cut chair backrests and formed frame profiles for modern office and hospitality furniture.",
      imageUrl: "/images/cap_custom_fabrication.jpg",
      featured: false,
      displayOrder: 42,
    },
    {
      name: "Bench Frame",
      categorySlug: "furniture-interior-components",
      industry: "Furniture, Construction",
      processes: "Sheet Metal Fabrication",
      materials: "Mild Steel (MS)",
      applicationType: "Job Work",
      description: "Heavy-duty commercial and park bench frames fabricated with weather-resistant anti-corrosive finishes.",
      imageUrl: "/images/cap_prototype_bulk.jpg",
      featured: false,
      displayOrder: 43,
    },
    {
      name: "Cabinet Frame",
      categorySlug: "furniture-interior-components",
      industry: "Furniture, Architecture & Interior",
      processes: "Laser Cutting + CNC Bending",
      materials: "CRCA / Galvanized Sheet",
      applicationType: "OEM Component",
      description: "Precision-folded modular metal storage cabinet chassis with knock-down assembly slots.",
      imageUrl: "/images/portfolio_enclosure.jpg",
      featured: false,
      displayOrder: 44,
    },
    {
      name: "Drawer Unit",
      categorySlug: "furniture-interior-components",
      industry: "Furniture",
      processes: "Laser Cutting + CNC Bending",
      materials: "CRCA / Mild Steel (MS)",
      applicationType: "Standard Product",
      description: "Sheet-metal drawer boxes and runners engineered with tight clearance tolerances for smooth sliding.",
      imageUrl: "/images/cap_custom_fabrication.jpg",
      featured: false,
      displayOrder: 45,
    },
    {
      name: "Shelf Bracket",
      categorySlug: "furniture-interior-components",
      industry: "Furniture, Architecture & Interior",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / Stainless Steel (SS)",
      applicationType: "Job Work",
      description: "Floating shelf brackets and heavy cantilever supports laser cut with integrated wall mounting holes.",
      imageUrl: "/images/portfolio_heavy_bracket.jpg",
      featured: false,
      displayOrder: 46,
    },
    {
      name: "Retail Display Stand",
      categorySlug: "furniture-interior-components",
      industry: "Furniture, General Engineering",
      processes: "Sheet Metal Fabrication",
      materials: "Mild Steel (MS) / CRCA",
      applicationType: "Custom Fabrication",
      description: "Point-of-purchase merchandise display racks and branding stands with modular hanging slots.",
      imageUrl: "/images/cap_prototype_bulk.jpg",
      featured: false,
      displayOrder: 47,
    },
    {
      name: "Display Rack",
      categorySlug: "furniture-interior-components",
      industry: "Furniture, Industrial Machinery",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / GI",
      applicationType: "Job Work",
      description: "Industrial warehouse and supermarket display shelving with slotted vertical uprights and folded trays.",
      imageUrl: "/images/cap_prototype_bulk.jpg",
      featured: false,
      displayOrder: 48,
    },

    // 07. Agriculture & Equipment (6 items)
    {
      name: "Agricultural Machine Bracket",
      categorySlug: "agriculture-equipment",
      industry: "Agriculture, Industrial Machinery",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS)",
      applicationType: "Job Work",
      description: "Heavy structural brackets for harvesters, seeders, and threshers designed to resist tough field conditions.",
      imageUrl: "/images/about_metal_part.jpg",
      featured: false,
      displayOrder: 49,
    },
    {
      name: "Tool Box",
      categorySlug: "agriculture-equipment",
      industry: "Agriculture, Automotive",
      processes: "Sheet Metal Fabrication",
      materials: "CRCA / Galvanized Sheet",
      applicationType: "Standard Product",
      description: "Weatherproof tractor and farm trailer toolboxes with lockable latches and internal partitioning.",
      imageUrl: "/images/portfolio_enclosure.jpg",
      featured: false,
      displayOrder: 50,
    },
    {
      name: "Hopper",
      categorySlug: "agriculture-equipment",
      industry: "Agriculture, Industrial Machinery",
      processes: "Sheet Metal Fabrication",
      materials: "Stainless Steel (SS) / Mild Steel (MS)",
      applicationType: "Custom Fabrication",
      description: "Conical and pyramid shaped grain and fertilizer hoppers formed on 160-ton CNC press brake with smooth interior welds.",
      imageUrl: "/images/cap_custom_fabrication.jpg",
      featured: false,
      displayOrder: 51,
    },
    {
      name: "Agricultural Blade",
      categorySlug: "agriculture-equipment",
      industry: "Agriculture",
      processes: "Laser Cutting",
      materials: "High Carbon Steel / Mild Steel (MS)",
      applicationType: "OEM Component",
      description: "Precision fiber laser profiled rotary cutter and mower blades manufactured with tight balance tolerances.",
      imageUrl: "/images/about_metal_part.jpg",
      featured: false,
      displayOrder: 52,
    },
    {
      name: "Tiller Blade",
      categorySlug: "agriculture-equipment",
      industry: "Agriculture",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / Stainless Steel (SS)",
      applicationType: "OEM Component",
      description: "Formed rotary tiller tines and soil cultivators with precision bevel edges for minimal soil drag.",
      imageUrl: "/images/cap_cnc_bending.jpg",
      featured: false,
      displayOrder: 53,
    },
    {
      name: "Machine Cover",
      categorySlug: "agriculture-equipment",
      industry: "Agriculture, Industrial Machinery",
      processes: "Laser Cutting + CNC Bending",
      materials: "CRCA / Mild Steel (MS)",
      applicationType: "Job Work",
      description: "Protective tractor bonnet panels and combine harvester side shields with air intake louvers.",
      imageUrl: "/images/cap_custom_fabrication.jpg",
      featured: false,
      displayOrder: 54,
    },

    // 08. General Engineering & Job Work (6 items)
    {
      name: "Custom Laser Cut Part",
      categorySlug: "general-engineering-job-work",
      industry: "General Engineering, Industrial Machinery",
      processes: "Laser Cutting",
      materials: "Mild Steel (MS) / Stainless Steel (SS) / Aluminium",
      applicationType: "Job Work",
      description: "High precision 2D fiber laser profiled components from DXF/DWG files with ±0.05mm dimensional accuracy.",
      imageUrl: "/images/cap_laser_cutting.jpg",
      featured: true,
      displayOrder: 55,
    },
    {
      name: "Custom CNC Bent Part",
      categorySlug: "general-engineering-job-work",
      industry: "General Engineering, Automotive",
      processes: "CNC Bending",
      materials: "Mild Steel (MS) / Aluminium / Stainless Steel (SS)",
      applicationType: "Job Work",
      description: "Multi-stage precision CNC press brake bending for prototypes and production runs up to 160 tons capacity.",
      imageUrl: "/images/cap_cnc_bending.jpg",
      featured: true,
      displayOrder: 56,
    },
    {
      name: "Fabricated Sheet Metal Bracket",
      categorySlug: "general-engineering-job-work",
      industry: "General Engineering, Industrial Machinery",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / CRCA / GI",
      applicationType: "Job Work",
      description: "Custom mounting plates and structural connection brackets fabricated with deburring and chamfered edges.",
      imageUrl: "/images/portfolio_heavy_bracket.jpg",
      featured: false,
      displayOrder: 57,
    },
    {
      name: "Mounting Plate",
      categorySlug: "general-engineering-job-work",
      industry: "General Engineering",
      processes: "Laser Cutting",
      materials: "Mild Steel (MS)",
      applicationType: "Job Work",
      description: "Base mounting flanges and foundation plates with precision counter-sunk and threaded holes.",
      imageUrl: "/images/about_metal_part.jpg",
      featured: false,
      displayOrder: 58,
    },
    {
      name: "Support Plate",
      categorySlug: "general-engineering-job-work",
      industry: "General Engineering, Construction",
      processes: "Laser Cutting + CNC Bending",
      materials: "Mild Steel (MS) / Stainless Steel (SS)",
      applicationType: "Job Work",
      description: "Structural angle stiffeners and gusset reinforcement plates cut and folded to engineering drawings.",
      imageUrl: "/images/portfolio_heavy_bracket.jpg",
      featured: false,
      displayOrder: 59,
    },
    {
      name: "Custom Sheet Metal Enclosure",
      categorySlug: "general-engineering-job-work",
      industry: "General Engineering, Industrial Machinery",
      processes: "Sheet Metal Fabrication",
      materials: "CRCA / Stainless Steel (SS) / Aluminium",
      applicationType: "Custom Fabrication",
      description: "Turnkey sheet metal assemblies tailored from customer 3D models with PEM hardware, stud welding, and finishing.",
      imageUrl: "/images/portfolio_enclosure.jpg",
      featured: false,
      displayOrder: 60,
    },
  ];

  for (const item of portfolioItems) {
    const slug = slugify(item.name);
    const categoryId = categoryMap[item.categorySlug];

    if (!categoryId) continue;

    const existingItem = await prisma.portfolioItem.findFirst({
      where: {
        OR: [{ slug }, { name: item.name }],
      },
    });

    if (existingItem) {
      await prisma.portfolioItem.update({
        where: { id: existingItem.id },
        data: {
          name: item.name,
          slug,
          categoryId,
          industry: item.industry,
          processes: item.processes,
          material: item.materials,
          materials: item.materials,
          applicationType: item.applicationType,
          description: item.description,
          imageUrl: item.imageUrl,
          featured: item.featured,
          status: "ACTIVE",
          displayOrder: item.displayOrder,
        },
      });
    } else {
      await prisma.portfolioItem.create({
        data: {
          name: item.name,
          slug,
          categoryId,
          industry: item.industry,
          processes: item.processes,
          material: item.materials,
          materials: item.materials,
          applicationType: item.applicationType,
          description: item.description,
          imageUrl: item.imageUrl,
          featured: item.featured,
          status: "ACTIVE",
          displayOrder: item.displayOrder,
        },
      });
    }
  }

  console.log(
    `Seeded ${portfolioItems.length} portfolio items across ${categories.length} categories.`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
